### ISSUE TITLE
The default accounts have incorrect password 

### ISSUE THREAD

**Issue by STommydx** [kylambg/COMP4111Phase2#1]
**Describe the bug**
The default accounts have incorrect password. To be specific, the accounts have passwords `passwdXXXXX` instead of `passXXXXX` required in the specification.

**To Reproduce**
1. Initialize the db with the SQLs given in `SQL_used`. In particular, `SQL_used/user_creation.sql` is the part that initializes the user accounts.
2. Login with the following payload
```json
{
	"Username": "user00001",
	"Password": "pass00001"
}
```

**Expected behavior**
`200 OK` with token returned

**What actually happens**
`400 Bad Request`

**Comment by kylambg** [comment]
Sorry, I forget to upload the readme file
Thank you for reminded me
