### ISSUE TITLE
Unable to setup project

### ISSUE THREAD

**Issue by Derppening** [kylambg/COMP4111Phase2#6]
### Issue description

Project fails to setup according to the README.

### Steps to reproduce this issue

1. Try to setup the database according to the README.

### What's the expected result?

No errors.

### What's the actual result?

When running `user_creation.sql`:
```
ERROR 1064 (42000) at line 19997: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '");
Insert into users(userId,UserName,Passwords)
Values(10000,"user10000","passw' at line 2
```

After fixing the above issue, when running `grant.sql`...
```
ERROR 1133 (42000) at line 1: Can't find any matching row in the user table
```

### Additional Information

You are missing a quotation mark here in `user_creation.sql`:
```diff
 Insert into users(userId,UserName,Passwords)
 Values(9998,"user09998","passwd09998");
 Insert into users(userId,UserName,Passwords)
-Values(9999,"user09999",passwd09999");
+Values(9999,"user09999","passwd09999");
 Insert into users(userId,UserName,Passwords)
 Values(10000,"user10000","passwd10000");
```

I have no idea how to fix the second issue.

~~Sidenote: Shouldn't the password be `pass00001` up to `pass10000`?~~
EDIT: I just noticed #1, which already mentions the issue.

**Comment by kylambg** [comment]
What is your environment? It runs fine on Window, at least for phase 1 and Tommy

**Comment by kylambg** [comment]
Maybe I transfer it to #7 , if you are running it on Linux.
I haven't test it on Linux

**Comment by Derppening** [comment]
I mean, the first part of the issue is a simple typo, and as such I am pretty certain it is affected on all systems.

As for the second part... Referring to [this](https://stackoverflow.com/questions/17597144/cant-find-any-matching-row-in-the-user-table) and [this](https://dev.mysql.com/doc/refman/5.7/en/grant.html), I think it may be because you don't explicitly create the user before granting it permissions?

For your reference, my development environment:
- Linux 5.6.15
- MySQL Server 5.7.30 (via Docker)
- OpenJDK 11.0.6

**Comment by kylambg** [comment]
I think the secone issue is owing to what you have said.
I have listed out the order of execution of those SQL file, you may refer to the README inside the file first

**Comment by Derppening** [comment]
The problem is, I was already using the execution flow you stated in `README.txt`. 

I have also tried replacing Step 4 with importing from `User-info.csv` provided by the TA, however neither works.

**Comment by kylambg** [comment]
I have fixed the first part and verified the second part does not exist after first part is fixed

**Comment by Derppening** [comment]
More information about the second part:

According to MySQL 5.7.7's release notes (in 2015-04-08):
> In MySQL 5.7.6, the `NO_AUTO_CREATE_USER` was deprecated. (It is preferable to create MySQL accounts with `CREATE USER` rather than `GRANT`.) Now the default SQL mode includes `NO_AUTO_CREATE_USER` and assignments to `sql_mode` that change the `NO_AUTO_CREATE_USER` mode state produce a warning, except assignments that set sql_mode to `DEFAULT`. `NO_AUTO_CREATE_USER` will be removed in a future MySQL version, at which point its effect will be enabled at all times (`GRANT` will not create accounts).

I don't see you adding creating database users at any point when executing the SQL scripts, and I don't see you modifying the `NO_AUTO_CREATE_USER` variable in the scripts either. Therefore, by running `GRANT` on non-existent users, I think that is where the issue lies.

To be honest, I don't know much about databases, but I don't think that step is necessary anyways...
